name: Deploy Feature Previews

on:
  push:
    branches:
      - "feature/**"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонуємо репозиторій
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Встановлюємо Node.js (якщо потрібен gulp чи збірка)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Встановлюємо залежності (якщо є)
      - name: Install dependencies
        run: npm ci

      # 4. Будуємо проєкт (якщо потрібен білд)
      - name: Build project
        run: npm run build || echo "No build step found"

      # 5. Генеруємо slug з назви гілки для папки прев’ю
      - name: Make safe branch slug
        id: slug
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          SLUG="$(echo "$BRANCH" \
            | tr '[:upper:]' '[:lower:]' \
            | sed -E 's#[^a-z0-9]+#-#g' \
            | sed -E 's#-+#-#g; s#^-##; s#-$##')"
          echo "SLUG=$SLUG" >> $GITHUB_ENV
          echo "Preview folder: $SLUG"

      # 6. Готуємо папку для деплою (без node_modules та системних файлів)
      - name: Prepare publish folder
        run: |
          mkdir publish
          rsync -av --progress ./ ./publish \
            --exclude node_modules \
            --exclude .git \
            --exclude .github \
            --exclude .vscode \
            --exclude .idea \
            --exclude .DS_Store

      # 7. Деплоїмо у gh-pages/previews/<branch>
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          destination_dir: previews/${{ env.SLUG }}
          enable_jekyll: true
